### ISSUE TITLE
Partition index in map_twix.py

### ISSUE THREAD

**Issue by aghaeifar** [pehses/twixtools#27] opened 2024-07-25 08:54 UTC
Hi

Regarding this line:
https://github.com/pehses/twixtools/blob/3cb702203e7a276df9ffe859502beb8e017795b4/twixtools/map_twix.py#L585

I noticed that in commit 6b83f6b56c5a1cc78a77cfca7773a4a5c8012ae4, the partition index was modified from -5 to -6. However, in the subsequent commit d83eb94b14919dc2d2be570bf6424311a4a2ce65 related to the implementation of PMU, it was changed back to -5.

Is this due to an inconsistency in the index between baselines? If so, we need to address this and check for the baseline, as my reconstruction routine breaks with the current state of twixtools.

Best,
Ali

**Comment by pehses** [comment] 2024-07-26 14:31
Hi Ali,

I looked into it, and it looks to me that -6 was actually correct. The '-5' would more or less deactivate this check which may have helped with the issue you encountered. However, I think that the root cause lies somewhere else.

It seems that the function list_indices() did not properly handle ranges - it's also possible that there was a change of behaviour from past python versions. Can you try the last commit from the [fix_range_issue](/pehses/twixtools/tree/fix_range_issue) branch and see if you still encounter this issue?

Btw, baselines shouldn't matter here. The shape of the data object is defined in map_twix. I originally choose this "inverted" order (compared to matlab) by accounting for the memory order (row-major as in C, not column-major as in Fortran/matlab). This has a few performance implications, e.g. ffts for oversampling reduction are faster when applied to the last (Col) dimension. However, in the end these performance issues can also be solved differently, so it's a bit of a relict. I was already thinking about making the array order more flexible and maybe even definable by the user (all the empty dims are sometimes a bit annoying, too), but I did not find time to do so.

Best,
Philipp

**Comment by aghaeifar** [comment] 2024-07-26 18:12
Hi Philipp,

Thanks for quickly looking into and patching this issue. I can confirm that the `fix_range_issue` branch has resolved the problem.

BTW, I am quite happy with the current indexing style. :)

Best,
Ali

**Comment by pehses** [comment] 2024-07-29 10:38
Great, i will then merge the changes to the main branch.

**Comment by pehses** [comment] 2024-07-29 10:39
Resolved with PR #28.

**Comment by pehses** [comment] 2024-07-29 10:39
Resolved with PR https://github.com/pehses/twixtools/pull/28.

**Closed by pehses** 2024-07-29 10:39 UTC
